### ISSUE TITLE
Replacement of Moment.js

### ISSUE THREAD

**Issue by martinhalford** [accordproject/technical-steering-committee#15]
# Discussion 🗣
Accord needs to replace Moment.js. Diana Lease has done some great work investigating replacement options.  Diana presented findings at the Tech WG on Wed 28-October comparing Moment.js with Day.js and Luxon. She is recommending Day.js

## Context
Moment.js is being deprecated. Moment.js is used throughout the Accord stack. A replacement library will need to implemented at some stage to replace the deprecated Moment.js stack.

## Detailed Description
See [issue #205](https://github.com/accordproject/concerto/issues/205) and TechWG Call Recording for 28-Oct for further details.

**Comment by jeromesimeon** [comment]
Technology WG has discussed this issue at length and decided to switch from `moment` to `dayjs`.

Initial change is already in Concerto 1.0. See corresponding PR here: https://github.com/accordproject/concerto/pull/218

Rest of the AP stack still needs to be migrated (notably Cicero and Ergo)

**Comment by martinhalford** [comment]
Handled by Tech WG. Resolved.
