### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by irmerk** [accordproject/technical-steering-committee#16]
# Discussion 🗣
Proposal for Accord Project to participate in [GSoC 2021][gsoc2021]

### GSoC Goal

> Bring new, diverse contributors into your communities that stay in your communities after their GSoC program ends.

---

#### 1. Smaller Project Size
All students participating in the 2021 program will be working on a **175** hour project instead of a **350** hour project. This change will also result in a few other changes including the **student stipend being cut in half**.
- Currently GSoC is missing out on many wonderful students who could never commit to such a huge project and time commitment but would be great contributors to our community. This is a significant change as GSoC now are no longer strongly encouraging students to focus only on GSoC over their summer. Students have many other responsibilities especially during the pandemic that make it hard for them to spend 30 hours a week on a project.
- The mentor stipends will be adjusted to **$400** per student mentored. In feedback from the mentor summit it was pointed out that the effort from mentors will not be half as much even though the project size is cut in half so GSoC adjusted from **$250** to **$400**.

#### 2. Shortened Coding Period
The **_coding period will be 10 weeks_** with a lot more flexibility for the mentor and student to decide together how they want to spread the work out over the summer. Some folks may choose to stick to a 17-18 hour a week schedule with their students, others may factor in a couple of breaks during the program (for student and mentor) and some may have students focus 30 hours a week on their project so they wrap up in 6 weeks. This also makes it a lot easier for students with finals or other commitments (weddings, etc.) to adjust their schedules.

#### 3. Two Evaluations (instead of three)
There will be an evaluation after 5 weeks and the final evaluation will take place after the 10th week. GSoC is also no longer requiring students complete their first evaluation (though GSoC encourages them to do so), so if a student doesn’t complete the first evaluation they will not automatically be removed from the program. They are still required to complete the final evaluation.

#### 4. Eligibility Requirements
In 2020 there are many ways students are learning and GSoC wants to acknowledge that so GSoC will be allowing students who are 18 years old AND currently enrolled (or accepted into) a post-secondary academic program as of May 17, 2021 or have graduated from a post-secondary academic program between December 1, 2020 and May 17, 2021 to apply to the GSoC program.

#### 5. Summary
What this means is that now the program will be open to folks participating in a variety of different academic programs, not just accredited university programs. This includes licensed coding camps, community colleges, and many other programs that may not be accredited yet but are post-secondary academic programs. 

---

These changes were made to help find more diverse students who GSoC hopes will stay involved in our communities after their GSoC ends. 

### 2020
- [Accord Project's Google Summer of Code Project Page][2020gsocPage]
- [Accord Project's Ideas List][2020ideasList]
- [Accord Project's News Announcement][2020apNews]

## Detailed Description

The program [announcement][announce], [timeline][timeline], [marketing materials][market] (slide deck, flyers), [FAQs][faq], and [short videos][videos] with tips for mentors and students are all available. You'll also notice the 2020 program has now been [archived][archive].

#### Organizations
If we would like to apply for the 2021 program please start thinking about the ~175 hr projects you would like students to work on and also reach out to our community members to ask if they would like to be mentors for the program. Having a thorough and well thought out list of Project Ideas is the most important part of our application. 

Encourage other open source orgs to apply -- Please also consider encouraging other open source projects to apply and be a first time GSoC org - we’re hoping to accept more orgs in 2021 than ever before with a good number of them being first time orgs. When orgs apply they can put our org down as a reference.

Please note that Org applications will open on **_January 29th_**. 

[2020gsocPage]: https://summerofcode.withgoogle.com/archive/2020/organizations/5947521500708864/
[2020ideasList]: https://github.com/accordproject/techdocs/wiki/Google-Summer-of-Code
[2020apNews]: https://accordproject.org/news/google-summer-of-code/
[gsoc2021]: http://g.co/gsoc
[announce]: https://opensource.googleblog.com/2020/10/google-summer-of-code-2021-is-bringing.html
[timeline]: https://developers.google.com/open-source/gsoc/timeline
[market]: https://developers.google.com/open-source/gsoc/resources/marketing
[faq]: https://developers.google.com/open-source/gsoc/faq
[videos]: https://developers.google.com/open-source/gsoc/videos
[archive]: https://summerofcode.withgoogle.com/archive/2020/organizations/

**Comment by sparkingdark** [comment]
hey @irmerk how to join Accordproject,is their any slack community available where I can ask question regarding this?

**Comment by irmerk** [comment]
@sparkingdark yes this is the link to our Slack: https://accord-project-slack-signup.herokuapp.com/

**Comment by sparkingdark** [comment]
Actually I try to do but got error regarding a email domain listed there

**Comment by irmerk** [comment]
## Update from GSoC:

If we would like to apply for the 2021 GSoC program, please start thinking about the **~175 hr projects** we would like students to work on and also reach out to our community members to ask if they would like to be mentors for the program. Having a thorough and well thought out list of [Project Ideas](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list) is the most important part of our application.

Many of our project ideas from our previous GSoC Ideas List were based on a 350 hour size project, so please look at ways to either break the project into smaller chunks or consider completely new project ideas that will be ~175 hours for students to work on over the summer.

We can check out the [2021 GSoC Org Application Questions](https://docs.google.com/document/d/1REKWPUUurpDVb7HWlxXjqC2BKIPtJLGEd1Rp9x3Jzeo/edit?usp=sharing) if we’d like to start preparing our responses in advance so we can copy over our answers once the org applications open Jan 29 - Feb 19 at [g.co/gsoc](http://g.co/gsoc) - there are a few new questions this year.

**Note**: Please encourage other open source orgs to apply -- if you know of other open source projects that may be interested in applying to GSoC as a first time org please remind them to check out the available resources below and have them put our org (or you) down as a reference.

#### Open source projects can [apply](https://summerofcode.withgoogle.com/) to be mentoring organizations from January 29th - February 19th at 1900 UTC.

Resources:
- [Mentor Guide](https://google.github.io/gsocguides/mentor/)
- [Timeline](https://developers.google.com/open-source/gsoc/timeline)
- [FAQs](https://developers.google.com/open-source/gsoc/faq)
- [Roles and Responsibilities](https://developers.google.com/open-source/gsoc/help/responsibilities)
- [Marketing Materials](https://developers.google.com/open-source/gsoc/resources/marketing) (slide deck, flyers)
- [Videos](https://developers.google.com/open-source/gsoc/videos)

**Comment by sparkingdark** [comment]
Somehow I can't able to join the slack.any solution.

**Comment by sparkingdark** [comment]
@irmerk I would like to more about Natural Language Legal Clause Detection.Can you help? I don't receive the slack invite it showing listed not in domain.

**Comment by irmerk** [comment]
@sparkingdark we are looking into the fix.

**Comment by irmerk** [comment]
This is capture in the [Techdocs Wiki](https://github.com/accordproject/techdocs/wiki/Google-Summer-of-Code-2021)

**Comment by irmerk** [comment]
# Context from GSoC:

### Be Prepared for Student Inquiries!
Over the next few weeks you'll be meeting potential students. Be prepared and responsive! Students who engage with their organization early (and often) are more likely to be accepted and then succeed. We encourage you to get to know the students and help them get to know you! Please continue to flesh out your ideas lists and documentation over the next few weeks.

### What is Expected of Org Admins
We have created a [GSoC 2021 Org Admin Help Doc](https://developers.google.com/open-source/gsoc/help/oa-tips) which has a detailed list of expectations with additional context for Org Admins to clarify your role and also to provide you with some helpful information to get your org and mentors off to a smooth start for GSoC 2021.

In addition, you'll also want to address these points below around your Org's Profile on the GSoC site (which is now live for all to see).

- Ensure that your organization's profile page is complete and accurate.
- Keep your Project Ideas List up to date and easy to access. And note that even if you have updated your list for the smaller 2021 project size, if the page says 2020 anywhere on it there will be confusion (already some students have emailed us about concerns the projects haven't been resized because it says 2020).
- Some Orgs currently have ideas lists that are buried two or three clicks underneath the provided link. We strongly encourage you to make the ideas front and center on the page the link points to.
- Make sure your logo looks good on the site. A logo that contains the organization name in readable letters is suggested. You may also need to tweak the aspect ratio.
- Verify the short description makes sense on the main organizations list. This is very important for grabbing attention quickly. Look at other organizations for examples.
- Ensure that the "Application Instructions" for students is thorough and complete.
- Communicate with prospective students about possible project ideas. Mentors should be helping too.
Invite mentors to your org (see more below). Make sure you have enough mentors to handle the amount of students showing interest.

### Changes to GSoC Program for 2021
If you participated last year these are the new changes for 2021. If the last time you or your org participated in GSoC was 2019 or before then please be sure to read all the help docs and [Program Rules](https://summerofcode.withgoogle.com/rules/) and [FAQs](https://developers.google.com/open-source/gsoc/faq) as multiple things have changed over the last few years, don't assume things are all the same (they aren't : )).

- The biggest change of course is that all student projects should be 175 hours (not 350 hours as in the past 16 years).
- The coding period is 10 weeks (instead of 12) which will allow more flexibility for the mentors and students to allow for a week or two break or to adjust the schedule around exams, previous commitments, or to finish earlier.
- We've opened up the eligibility to allow for more folks to be eligible to apply for GSoC - now any student over 18 years old enrolled in a post-secondary academic program or who has graduated from such a program between Dec 1, 2020 and May 17, 2021 can apply for GSoC. We also are allowing folks who have been accepted into a post-secondary academic program that begins by September 30, 2021 to apply.
- Organizations that are part of a government will not receive any mentor stipends for GSoC as described in the Program Rules.
- For orgs who need to change their financial details for GSoC 2021, the deadline to have all of your Payoneer account information completed is July 15, 2021 as described in the Program Rules. We will not pay out stipends to any orgs who miss this hard deadline. We'll send more details about receiving stipends etc. in mid-April so you'll have 3 months to get everything in order.

### Inviting Mentors to your Org
Org Admins should now be sending potential mentors invitations to be a part of their organization. The mentor will need to click the link in the email they receive to accept the invitation and create their account. _All mentors must be invited by an Org Admin_.

**Comment by irmerk** [comment]
# Important Changes to GSoC for 2021

If you are new to GSoC then you should read the [Program Rules](https://summerofcode.withgoogle.com/rules/), [FAQs](https://developers.google.com/open-source/gsoc/faq) and at least scan through the [GSoC Mentor Guide](https://google.github.io/gsocguides/mentor/). If you have participated in GSoC in the last couple of years we are pointing out the changes to the program below, but again, never assume something is the same as the time you participated X years ago. Things do evolve and GSoC is no different.

### [Action Required for Mentors] Please take the time to do the following:

- Reach out to your organization administrator to learn more about what is expected of you this year as a mentor, including reviewing the student proposals and leaving comments starting March 29.
- Read the [Google Summer of Code mentor guide](Google Summer of Code mentor guide) and the [Roles and Responsibilities](https://developers.google.com/open-source/gsoc/help/responsibilities) doc to help you understand what is expected of you over the next 6 months.
- Watch the 5 minute YouTube video: "[Being a Great GSoC Mentor](https://www.youtube.com/watch?v=3J_eBuYxcyg)". The video was shot with GSoC veteran Org Admins and Mentors. It contains helpful information about the program and how to participate successfully at each step in GSoC.

(@dselman @martinhalford @tbrooke @algomaster99 @dianalease @michael-grover @niallroche @latticecut)

### [Action Required for Org Admins] Please take the time to do the following:

- You should currently be inviting mentors and making sure they are registering so the mentors will have access to the student proposals at the end of the month so they can comment and help with the review process.
- Be sure you have enough mentors to support the incoming student proposals over the next few weeks.
- If your org has a particular process for reviewing student proposals be sure all mentors are aware of it.

(@jeromesimeon @irmerk)

---

## Student Proposals

#### Student Proposal Submission period: March 29 - April 13
Starting March 29, students will be able to submit their proposals via the program website. **Each student may submit up to 3 proposals to the program**. They can submit multiple proposals to the same organization for different projects if they wish.

Historically, the students with the best proposals reach out to the orgs early to receive feedback before submitting their final proposal - those students who have already been reaching out to you are likely to be among your best student options this year.

_Influx of student inquiries this year?_
Many Org Admins have seen a huge increase in students reaching out in this pre-application period this year and mentors are struggling to reply to applicants. Some students can be impatient so we encourage you to put something on your Ideas List or in your Application Instructions (on Org's profile page) stating mentors will do their best to reply to all students but due to a huge increase in student interest this year they may not be able to respond to all inquiries. You could also have an auto-responder or some sort of canned response to let students know you are looking at their proposals but it could take X days to receive a response.

When the application period opens March 29th you can expect an even larger number of applicants and questions so your org should figure out how you want to handle these. You will receive some emails from students that are generic or possibly ‘spammy', feel free to ignore those.

_Draft Proposals_
To encourage more students to seek feedback on their proposals, draft proposals are part of the official proposal workflow. Be sure to refresh your dashboard periodically so that you can see when new drafts are ready to review. You will not receive an email. We are encouraging the use of Google Docs for proposals as this will allow you to comment directly on the proposal.

#### Post Student Proposal Period: April 13 - May 2
Students **must** submit their final proposal as a PDF through the website. It will be visible to mentors/org admins after the deadline for student applications (April 13 18:00 UTC). You should make your decisions on which students to accept based on the contents of the final PDF proposal and your interactions with the student.

Students can delete their proposals after the submission period and you will not receive an email of the deletion. If a proposal disappears from your list, it is likely because they deleted it or because they failed to submit a Final PDF.

#### Working with Students
All student projects must have at least one mentor assigned. We strongly encourage assigning a second mentor as a backup mentor or co-mentor. A mentor should not be the primary mentor for more than one or two students maximum. Mentoring can be a lot of work and we don't want anyone to burn out and become frustrated with the program.

**Comment by irmerk** [comment]
# Update from Google Summer of Code

The student submission period is now over. We had 4,771 students submit their final proposals for GSoC 2021. Thank you all for spending considerable time and care to work with students during the application period (and before) to help them understand more about your org and the project ideas your org is interested in having students work on this summer.

In this phase of GSoC (Proposal Review and Slot Requests), your org will look through all the student proposals and choose which ones your org wishes to select as GSoC student projects for 2021. You will also be determining which mentors can commit to mentoring which student projects so your org admins can make the org slot requests before May 3.

### Reviewing Final PDF Proposals: April 13 - May 2

You should now be able to see the Final PDFs submitted by students.

You may have been chatting with students these past couple of weeks but you no longer see their proposal in the system for you to select, that could be because they failed to submit a final pdf and/or their proof of enrollment forms or they removed themselves from the program. Students without a Final PDF proposal and their proof of enrollment cannot be accepted, there are no exceptions.

Your decision about whether or not to select a student should be based on the Final PDF proposal. You will also be able to reference the draft proposal -- but should not make your decision based on it. A draft proposal is intended to be used to view the comment thread and maybe see how the student interacted with you and responded to comments, etc. Do not use it to let the student make more changes after the deadline. That is not fair to all the other applicants.

### Want to Mentor?

If you are interested in being a mentor for a given proposal then you can click the purple "Want to Mentor" button to help your Org Admin know that you are interested. This is particularly helpful for the org admins when determining if they have enough mentors for their slot requests.

**IMPORTANT: We suggest projects have 2, and even 3, mentors ready to help mentor each student project this year**. 1 mentor should be considered the primary mentor (responsible for evaluations, etc.) and the other 1-2 mentors should help mentor as much as they can and be ready to step in should the primary mentor need to take some time off for any period of time at any point in the program.

### Frequently Asked Questions about Mentoring

**Can I mentor multiple students?**
The general advice from other mentors is it's best to mentor 1 student and focus on that student so you can give them your full attention, but it's okay to maybe be a backup mentor for a second project. Don't spread yourself too thin or it will be a bad experience for everyone - you, the student, and the org.

There isn't a rule against mentoring multiple students but if this is your first time mentoring you definitely should only mentor 1 student.

**As the primary mentor, how much time will I be spending mentoring a student?**
This all depends on the project and the student, time commitments can vary.

Generally you can assume that during the community bonding period you will want to commit 5+ hours a week to get the student set up for success and integrated into your community. Once coding begins, you should be prepared to spend 2.5 - 4 hours reviewing the student's work, giving feedback, answering questions, having video chats, etc. with the student.

### Ineligible Students

1. Remember per the Program Rules, Orgs can not accept students who are immediate family members or in the same household as any org admins or mentors for your organization.
1. If you were talking with a student during the student application period and they didn't submit a final proposal or proof of enrollment then they are not eligible to be accepted (they will not appear in your dashboard of proposals either).

### Quick Glossary

- **Slot**: Google will grant each org a certain number of project “slots” based on requests and history with GSoC. Each slot can hold one student/project. 
- **Project**: Once a student has been selected and projects are announced, their proposal becomes a project for the remainder of the program.

### Slots Request - deadline Monday, May 3 18:00 UTC (Org Admin responsibility)

- Org Admins will request a minimum and maximum number of project slots.
- Slots should only be requested for projects where there is at least one confirmed mentor (and 1 backup mentor) and where the student has a good chance of succeeding.
- Do not accept "okay" proposals.
- Do not request more slots than you have mentors for - if we grant you the slots you request and you can't use all of them you have essentially taken away these slots from other orgs that could have used them and also taken away the opportunity for that number of students to participate in GSoC 2021.
- New orgs will likely only receive 1-2 slots, no matter how many they request.

All Org Admins should read [Slot Allocation and Project Selection](https://developers.google.com/open-source/gsoc/help/slot-allocation) for more detailed information.

**Comment by martinhalford** [comment]
From TSC Meeting: Thursday 29 April, 2021:

- Student proposals have been received by AP mentors.
- Mentors have shortlisted proposals. 
- AP are submitting Project Slot requests for selected proposal to Google - due Monday, 3 May at 18:00 UTC.
- Google will then advise success of Project Slot requests on 17 May

**Comment by martinhalford** [comment]
From TSC Meeting: Thursday 27 May, 2021:

- Has kicked off and number of mentor / student meetings held.
- Some administrative questions regarding mentor payments from Google. 
- Suggested Clause.io collect GSoC mentor payments on behalf of the Accord Project.

**Comment by martinhalford** [comment]
From TSC Meeting: Thursday 24 June, 2021:
- Students and mentors gavce presentations at Tech WG Meeting on Wed June 23rd.
- Presentations were high quality from all three (3) projects.

**Comment by martinhalford** [comment]
From TSC Meeting: Thursday 26 Aug, 2021:
- Three projects completed. All went well and all students were passed.
1. Template and Contract Signing (Sanket - Mentors: Jerome, Tom, Nikolay & Martin)
2. OOXML Transform (Kushal - Mentors: Dan and Aman)
3. AI/Machine Learning (Eason - Mentor: Niall)

Thank you to Matt (for organising) and all mentors for providing support and advice.
