### ISSUE TITLE
Setting up dependabot 

### ISSUE THREAD

**Issue by Cronus1007** [accordproject/technical-steering-committee#27]
# Discussion 🗣
Dependabot alleviates that pain by updating your dependencies automatically, so you can spend less time updating dependencies and more time building. Up until now, the Dependabot features we’ve brought to GitHub have focused on automated security updates, which update packages that have known vulnerabilities.
## Context
When you check in an insecure dependency, or a new vulnerability is discovered in a dependency you already have, we already let you know with security alerts for vulnerable dependencies. This system also powers our automated security updates, which we announced last November. GitHub users have merged more than 776,000 automated security update pull requests since the announcement.

**Comment by irmerk** [comment]
Which repositories do not have Dependabot that could be benefited from it?

**Comment by Cronus1007** [comment]
The web-components repository can be benefitted from it. Plzzz have a look upon this PR. Same feature can be implemented to the web components repository https://github.com/accordproject/hlf-cicero-contract/pull/11

**Comment by Cronus1007** [comment]
@irmerk Any opinions or suggestion you want to add here?

**Comment by mttrbrts** [comment]
I've now enabled dependabot for all Accord Project repositories. Thanks for the prompt @Cronus1007!

![image](https://user-images.githubusercontent.com/7544022/111783630-4f3ebd00-88b2-11eb-84a1-e1f40c423958.png)

**Comment by Cronus1007** [comment]
@mttrbrts Have a look upon these issues as well. #25 #26 #24
