### ISSUE TITLE
AP Summer of Code 2022

### ISSUE THREAD

**Issue by irmerk** [accordproject/technical-steering-committee#32]
# Discussion 🗣
Proposal for Accord Project to participate in [GSoC 2022][gsoc2022]

## Context

While this is still early, GSoC has [2022 Timeline information][2022timeline] up.

### GSoC Goal

> Bring new, diverse contributors into your communities that stay in your communities after their GSoC program ends.

---

### Changes

This year's changes have recently been [announced][announce]:

#### 1. Expanding eligibility
GSoC is opening the program up to all newcomers of open source that are 18 years and older. The program will no longer be solely focused on university students or recent graduates. This targets people at various stages of their career, recent career changers, self-taught, those returning to the workforce, etc.

#### 2. Multiple Sizes of Projects
GSoC will support both medium sized projects (~175 hours) and large projects (~350 hours).

#### 3. Increased Flexibility of Timing for Projects
GSoC is allowing for considerable flexibility in the timing for the program. The project can be spread out over a longer period of time and can even switch to a longer timeframe mid-program. Rather than a mandatory 12-week program that runs from June – August with everyone required to finish their projects by the end of the 12th week, GSoC is opening up so mentors and their GSoC Contributors can decide together if they want to extend the deadline for the project up to 22 weeks.

---

See previous years' material:

### 2021
- https://github.com/accordproject/technical-steering-committee/issues/16
- [**Project**: Automatic Identification and Classification of Contract Data Types with NLP][proj1]
- [**Project**: Digital Signatures][proj2]
- [**Project**: CiceroMark OOXML Roundtrip Conversion][proj3]
- [Accord Project's Student Announcement][studentAnnounce]

### 2020
- [Accord Project's Google Summer of Code Project Page][2020gsocPage]
- [Accord Project's Ideas List][2020ideasList]
- [Accord Project's News Announcement][2020apNews]

## Detailed Description

The program [timeline][timeline], [marketing materials][market] (slide deck, flyers), [FAQs][faq], and [short videos][videos] with tips for mentors and students are all available. You'll also notice the 2021 program has now been [archived][archive].

#### Organizations
If we would like to apply for the 2022 program please start thinking about the ~175 hr and ~350 hr projects we would like students to work on and also reach out to our community members to ask if they would like to be mentors for the program. Having a thorough and well thought out list of Project Ideas is the most important part of our application. 

Please note that Org applications will open in **_January 2022_**. 

[gsoc2022]: http://g.co/gsoc
[2022timeline]: https://developers.google.com/open-source/gsoc/timeline
[proj1]: https://accordproject.org/news/gsoc-2021-automatic-identification-and-classification-of-contract-data-types-with-nlp/
[proj2]: https://accordproject.org/news/gsoc-2021-digital-signatures-my-experience/
[proj3]: https://accordproject.org/news/gsoc-2021-ciceromark-ooxml-roundtrip-conversion/
[studentAnnounce]: https://accordproject.org/news/3-students-accepted-for-google-summer-of-code-2021/
[2020gsocPage]: https://summerofcode.withgoogle.com/archive/2020/organizations/5947521500708864/
[2020ideasList]: https://github.com/accordproject/techdocs/wiki/Google-Summer-of-Code
[2020apNews]: https://accordproject.org/news/google-summer-of-code/
[announce]: https://opensource.googleblog.com/2021/11/expanding-google-summer-of-code-in-2022.html
[timeline]: https://developers.google.com/open-source/gsoc/timeline
[market]: https://developers.google.com/open-source/gsoc/resources/marketing
[faq]: https://developers.google.com/open-source/gsoc/faq
[videos]: https://developers.google.com/open-source/gsoc/videos
[archive]: https://summerofcode.withgoogle.com/archive/2021/organizations/

**Comment by anmode** [comment]
@irmerk Would this year too accord project list itself in GSoC? Please may u tell me that in which project of accord projects should start open-source contribution?

**Comment by irmerk** [comment]
Unsure exactly what your question is @anmode, but [this guide](https://accordproject.org/code-contribution-guide) may be helpful for you.

**Comment by martinhalford** [comment]
- Project ideas list created.
- Application submitted by Matt.
- March 7 application should be accepted.

**Comment by anmode** [comment]
Ohh that's great

**Comment by martinhalford** [comment]
As the Accord Project was not accepted as a mentoring organisation for this year's GSoC, do we want to run our own "Accord Project Summer of Code"?  

We currently have USD $2,434 in the AP kitty and so, we could not afford to match GSoC stipends using only existing funds.  Therefore, we'd either need to be more modest with our stipends and/or attract extra funding from sponsors.

To be discussed at next TSC Meeting?

**Comment by martinhalford** [comment]
- The Accord Project was unsuccessful in being accepted to the Google Summer of Code for 2022.
- However, DocuSign and beNEXT have both committed to contributing USD $3,000 each, being USD $6,000 in total, in order to fund an "Accord Project Summer of Code" (working-title).
- Based on the GSoC format, this would be equivalent to 2 large projects or 4 small projects.
- Suggested that we follow the same format and process that Google uses for the Google Summer of Code, and replicate this for the APSoC.
- However, main question is: how do we promote the fact that AP is running a "Summer of Code" event and attract contributors.
- AP has attracted a few hundred members to the AP Discord channel with a percentage of these people expressing interest in being involved in the AP GSoC event.  We can, therefore, promote the APSoC event to these people via Discord.
- We can also advertise the APSoC on the AP web site and ask community members to promote this via social media and personal referrals. 
- **ACTION** 
	- Announce decision to community via Tech WG call and via web site.
	- @martinhalford to reach out to @mttrbrts to determine if he is willing to help continue running the process from an administrative perspective.
	- Encourage people to continue contributing to ["Ideas" document.](https://docs.google.com/document/d/1Ocx1-mkRadAoeikGkeOOdsMPCqmbmOnIrF1IJRX-8mc/edit)

**Comment by anton1s** [comment]
Tom and I met on this one. Our recommendation is to pause and wait for six months before re-engaging. 

Here is our reasoning: 

1. Low take-off growth for OneNDA so far (600 customers is tiny when everyone doing business out there is likely a NDA user). 
2. Claustack is still thinking of NDAs purely as standardized PDF documents. 
3. They don't have the means to host an Accord template 

In six months we will see where these guys are in terms of growth and we will try to re-engage differently; we want to explore whether they are (if growth is there) open to market oneNDA and an equivalent AP template as a package, potentially the same with onePDA and so on.

**Comment by dselman** [comment]
AP SoC is now well underway and seems to be progressing nicely. Can we close this?

**Comment by martinhalford** [comment]
As commented by @dselman - AP SoC is in progress and being managed accordingly.  Closing issue as requested.
