### ISSUE TITLE
[NOMINATION]: 2022 Tom Brooke

### ISSUE THREAD

**Issue by tbrooke** [accordproject/technical-steering-committee#38]
# Nomination 🗳️

## Tom Brooke
 Github: tbrooke

## Nominated By
Self

## Short Personal Bio
I am a practicing lawyer in North Carolina. I also code, primarily in Clojure. I taught coding for Lawyers for two semesters at Campbell University School of Law. I am a current member and past President of the North Carolina Bar Association Future of Law Committee. I am founder of North Carolina Legal Hackers and an active member and organizer in Legal Hackers.

## Short Personal Pitch

I have been on the TSC and I have followed and been involved with Accord Project almost from the start

**Comment by mttrbrts** [comment]
@tbrooke I'd be delighted to nominate you!
