### ISSUE TITLE
Notification of Accord Project Upcoming TSC Election

### ISSUE THREAD

**Issue by dselman** [accordproject/technical-steering-committee#47]
# Discussion 🗣

If you are tagged on this issue it means you are eligible to vote in the upcoming Accord Project TSC election.

## Context

We have tagged you on this issue to make you aware of the election.

## Detailed Description

Voting start at Sept. 18, 2022, 11:59 p.m.
Voting end at Sept. 25, 2022, 11:59 p.m.

To vote go to https://vote.heliosvoting.org and login with your GitHub ID.

Election process: https://github.com/accordproject/technical-steering-committee/wiki/Elections

Video: https://vimeo.com/750020939

## Eligible Voters

@0xpayne
@4katie
@98lenvi
@Aakash-Jakhmola
@AbhijithGanesh
@Alexandria
@Aniruddha-Shriwant
@Ashiroq
@Ayman161803
@Bharat123rox
@BjornvdLaan
@Brethland
@C0rWin
@CDharmateja
@Calasada
@Clintonio
@DEBSUBHRO
@DianaLease
@EdMoffatt
@EdProsser
@EllisHenderson
@Fanarito
@FelixKuehl
@Ian-Yy
@Innovator007
@Jakeeyturner
@James-Ronayne
@JamesBlandford
@Jeevan-Kiran-Lenka
@JoelLau
@Jonathan-Casey
@K-Kumar-01
@KL13NT
@KaiUsher
@KyleBastien
@Michael-Grover
@NathanHazout
@Navdevl
@NicBritz
@Niladri24dutta
@ODOWDAIBM
@OliverTod
@Parikshit-Hooda
@Ph0tonic
@PseudoNerd
@RNiordson
@RanadeepPolavarapu
@ScottMorris
@ShiroYacha
@ShrutikaSingh

**Comment by dselman** [comment]
@Sphar-io
@TC5022
@Tobias-Hunter
@TopJohn
@VishalS99
@Yash-Garg
@a4aditya
@abnazhor
@acshea
@adagys
@adecaro
@adnan-c
@adriaan-pelzer
@adrijshikhar
@agoldvarg
@ajmeraharsh
@akaila
@akshitsarin
@alexCatena
@algomaster99
@alvesgabriel
@amanag25
@amoothart
@andrearizzello
@andrew-coleman
@anusha5695
@archhhh
@ardelapaz
@armujahid
@arshadkazmi42
@arteevraina
@asararatnakar
@aviralwal
@awilts
@awjh-ibm
@bestbeforetoday
@bjornmorten
@bjrnt
@bucs-fan813
@capt-haddock
@cazfletch
@chevdor
@christo4ferris
@cmccandless
@codingdefined
@codinova-shivam
@contractpendev
@d-e-v-esh
@daniloff200
@davidkel
@davidleeuk
@defunctzombie
@denyeart
@dependabot[bot]
@devcer
@dlkconsultancy
@dohvis
@doomswatter
@doowb
@dsanchezseco
@dselman
@elit-altum
@emailnjv
@ericholscher
@erikbfeeley
@erin-hughes
@exFalso
@fabric-composer-app
@fboechats
@fenglianxu
@flagoon
@florenciasilva
@foolcage
@franchetteSymph
@frbrkoala
@gangachris
@gargarchit
@gatsinski
@gaurav7019
@github-actions[bot]
@glindsell
@hannahrayner
@harrika1982
@harrisob
@harsh1206
@hshadab
@husseyexplores
@iRohitSingh
@ilfrich
@inokawa
@irmerk
@ischasny
@j4m3sb0mb
@jamesgeorge007
@jamiels
@javiercanossini
@jbesq777
@jcarpenter67
@jdp1g09
@jeromesimeon
@jerrybuks
@jfrolich
@jimthematrix
@joeheyming
@johnnyqbui
@jorilallo
@jt-nti
@jwagantall
@jyellick
@kach
@kanav-raina
@kenjisiu-ibmhk
@kewbish
@kharaone
@ki0apa
@kokifpen
@krishvoor
@krtk6160
@ksachdeva
@ldesrosi
@lehors
@lesleyannjordan
@lex111
@lhaskins
@liam-grace
@lucasdf
@lukehedger
@m4tr1k
@manifestlifeinc
@manishprivet
@martinhalford
@mastersingh24
@mbtamuli
@mbwhite
@mengwong
@michizhou
@midhunbiju
@mikehearn
@miqh
@mitchstewart
@monika
@mttrbrts
@neeravarora
@niallroche
@nickgaski
@nicolapaoli
@nik72619c
@nikklein
@nithilan4
@nklincoln
@oorjitchowdhary
@opiepj
@parammittal16
@pards
@peara
@peterhunn
@petrgazarov
@pospi
@prakharsr
@pramodrhegde
@pranjalv9
@qualitymanifest
@rameshthoomu
@rennman
@rick-r3
@rogersanick
@rohitx007
@royshouvik
@rthatcher
@rustygloves
@ryanctlin
@ryjones
@sachdeva-shrey
@sachinr
@sahalsaad
@salmanbaset
@samjsmith
@sanketshevkar
@sanyamdogra
@sccheruku
@schmitty890
@sgbj
@shacshar
@shahsank3t
@shakti97
@shamsasari
@shubhangi013
@sidhyatikku
@simonghrt
@smithbk
@sstone1
@starblind
@stefanblaginov
@steffinstanly
@sumitkharche
@sumitks866
@suryalnvs
@susmitasomanchi
@tbrooke
@tijohnson
@tkuhrt
@tommoor
@torresjeff
@uchibeke
@utajum
@vaibhav111tandon
@varun-raj
@vipulbhj
@vitorduarte
@whitehawk0011
@winslet
@yacovm
@yuki-kon
@zachgoll
@zeesh-ali

**Comment by dselman** [comment]
@davidleeuk
@defunctzombie
@denyeart
@dependabot[bot]
@devcer
@dlkconsultancy
@dohvis
@doomswatter
@doowb
@dsanchezseco
@dselman
@elit-altum
@emailnjv
@ericholscher
@erikbfeeley
@erin-hughes
@exFalso
@fabric-composer-app
@fboechats
@fenglianxu
@flagoon
@florenciasilva
@foolcage
@franchetteSymph
@frbrkoala
@gangachris
@gargarchit
@gatsinski
@gaurav7019
@github-actions[bot]
@glindsell
@hannahrayner
@harrika1982
@harrisob
@harsh1206
@hshadab
@husseyexplores
@iRohitSingh
@ilfrich
@inokawa
@irmerk
@ischasny
@j4m3sb0mb
@jamesgeorge007
@jamiels
@javiercanossini
@jbesq777
@jcarpenter67
@jdp1g09
@jeromesimeon
@jerrybuks
@jfrolich
@jimthematrix
@joeheyming
@johnnyqbui
@jorilallo
@jt-nti
@jwagantall
@jyellick
@kach
@kanav-raina
@kenjisiu-ibmhk
@kewbish
@kharaone
@ki0apa
@kokifpen
@krishvoor
@krtk6160
@ksachdeva
@ldesrosi
@lehors
@lesleyannjordan
@lex111
@lhaskins
@liam-grace
@lucasdf
@lukehedger
@m4tr1k
@manifestlifeinc
@manishprivet
@martinhalford
@mastersingh24
@mbtamuli
@mbwhite
@mengwong
@michizhou
@midhunbiju
@mikehearn
@miqh
@mitchstewart
@monika
@mttrbrts
@neeravarora
@niallroche
@nickgaski
@nicolapaoli
@nik72619c
@nikklein
@nithilan4
@nklincoln
@oorjitchowdhary
@opiepj
@parammittal16
@pards
@peara
@peterhunn
@petrgazarov
@pospi
@prakharsr
@pramodrhegde
@pranjalv9
@qualitymanifest
@rameshthoomu
@rennman
@rick-r3
@rogersanick
@rohitx007
@royshouvik
@rthatcher
@rustygloves
@ryanctlin
@ryjones
@sachdeva-shrey
@sachinr
@sahalsaad
@salmanbaset
@samjsmith
@sanketshevkar
@sanyamdogra
@sccheruku
@schmitty890
@sgbj
@shacshar
@shahsank3t
@shakti97
@shamsasari
@shubhangi013
@sidhyatikku
@simonghrt
@smithbk
@sstone1
@starblind
@stefanblaginov
@steffinstanly
@sumitkharche
@sumitks866
@suryalnvs
@susmitasomanchi
@tbrooke
@tijohnson
@tkuhrt
@tommoor
@torresjeff
@uchibeke
@utajum
@vaibhav111tandon
@varun-raj
@vipulbhj
@vitorduarte
@whitehawk0011
@winslet
@yacovm
@yuki-kon
@zachgoll
@zeesh-ali

**Comment by dselman** [comment]
@jerrybuks
@jfrolich
@jimthematrix
@joeheyming
@johnnyqbui
@jorilallo
@jt-nti
@jwagantall
@jyellick
@kach
@kanav-raina
@kenjisiu-ibmhk
@kewbish
@kharaone
@ki0apa
@kokifpen
@krishvoor
@krtk6160
@ksachdeva
@ldesrosi
@lehors
@lesleyannjordan
@lex111
@lhaskins
@liam-grace
@lucasdf
@lukehedger
@m4tr1k
@manifestlifeinc
@manishprivet
@martinhalford
@mastersingh24
@mbtamuli
@mbwhite
@mengwong
@michizhou
@midhunbiju
@mikehearn
@miqh
@mitchstewart
@monika
@mttrbrts
@neeravarora
@niallroche
@nickgaski
@nicolapaoli
@nik72619c
@nikklein
@nithilan4
@nklincoln
@oorjitchowdhary
@opiepj
@parammittal16
@pards
@peara
@peterhunn
@petrgazarov
@pospi
@prakharsr
@pramodrhegde
@pranjalv9
@qualitymanifest
@rameshthoomu
@rennman
@rick-r3
@rogersanick
@rohitx007
@royshouvik
@rthatcher
@rustygloves
@ryanctlin
@ryjones
@sachdeva-shrey
@sachinr
@sahalsaad
@salmanbaset
@samjsmith
@sanketshevkar
@sanyamdogra
@sccheruku
@schmitty890
@sgbj
@shacshar
@shahsank3t
@shakti97
@shamsasari
@shubhangi013
@sidhyatikku
@simonghrt
@smithbk
@sstone1
@starblind
@stefanblaginov
@steffinstanly
@sumitkharche
@sumitks866
@suryalnvs
@susmitasomanchi
@tbrooke
@tijohnson
@tkuhrt
@tommoor
@torresjeff
@uchibeke
@utajum
@vaibhav111tandon
@varun-raj
@vipulbhj
@vitorduarte
@whitehawk0011
@winslet
@yacovm
@yuki-kon
@zachgoll
@zeesh-ali

**Comment by dselman** [comment]
@oorjitchowdhary
@opiepj
@parammittal16
@pards
@peara
@peterhunn
@petrgazarov
@pospi
@prakharsr
@pramodrhegde
@pranjalv9
@qualitymanifest
@rameshthoomu
@rennman
@rick-r3
@rogersanick
@rohitx007
@royshouvik
@rthatcher
@rustygloves
@ryanctlin
@ryjones
@sachdeva-shrey
@sachinr
@sahalsaad
@salmanbaset
@samjsmith
@sanketshevkar
@sanyamdogra
@sccheruku
@schmitty890
@sgbj
@shacshar
@shahsank3t
@shakti97
@shamsasari
@shubhangi013
@sidhyatikku
@simonghrt
@smithbk
@sstone1
@starblind
@stefanblaginov
@steffinstanly
@sumitkharche
@sumitks866
@suryalnvs
@susmitasomanchi
@tbrooke
@tijohnson
@tkuhrt
@tommoor
@torresjeff
@uchibeke
@utajum
@vaibhav111tandon
@varun-raj
@vipulbhj
@vitorduarte
@whitehawk0011
@winslet
@yacovm
@yuki-kon
@zachgoll
@zeesh-ali

**Comment by dselman** [comment]
@tkuhrt
@tommoor
@torresjeff
@uchibeke
@utajum
@vaibhav111tandon
@varun-raj
@vipulbhj
@vitorduarte
@whitehawk0011
@winslet
@yacovm
@yuki-kon
@zachgoll
@zeesh-ali

**Comment by mttrbrts** [comment]
@dselman to document lessons in the Election Wiki.
