### ISSUE TITLE
Standardise approach to static site hosting

### ISSUE THREAD

**Issue by dselman** [accordproject/technical-steering-committee#5]
Accord Project currently uses Netlify to host static websites.
- https://models.accordproject.org
- https://templates.accordproject.org
- https://ap-web-components.netlify.app
- http://docs.accordprojec.org

These static sites are automatically recreated when GitHub pull requests are created, and on a merge to the main branch.

All static sites should be hosted on AP paid for infrastructure.

**Comment by irmerk** [comment]
Are we using an open source version of Netlify already?

**Comment by martinhalford** [comment]
Jerome looking at creating an AP account in Netlify and possible alternatives.

**Comment by martinhalford** [comment]
Based on the assumption that the Accord Project needs to provide a reliable, relatively fast hosting service for some of the static web sites (in particular, models.accordproject.org) then it was proposed to that AP considers using AWS S3 Cloud Storage. 

AWS S3 buckets allow for the easy deployment and web hosting of static web sites (https://aws.amazon.com/s3/).  

When combined with AWS CloudFront (CDN) these S3 buckets can support HTTPS and fast delivery of content to users in any geography. (https://aws.amazon.com/cloudfront/)

**Pricing**
As AWS is a commercial service then there are costs involved.
- AWS CloudFront provides the first 1TB of data transfer for free per month.  After which it is $0.085 per 10 TB per month thereafter.  (i.e. 8.5 US cents per 10 TB per month).
- AWS S3 Storage is estimated to cost less than $0.23 per month based on an upper estimate of 10 GB of file storage.

![image](https://user-images.githubusercontent.com/970336/151457000-cc05b970-eaed-48b0-b624-9128d71705d5.png)

An AWS Account has been setup for Accord Project for testing.  A fork of the code base has been made for the "Models", "TechDocs", "Templates" and "Web Components" repos.

Will liaise with @mttrbrts and @jeromesimeon for further testing.

**Comment by martinhalford** [comment]
@mttrbrts @jeromesimeon - I've created individual user accounts for you both, with admin privileges, in AWS and have shared the credentials with you via Discord. 

You will see the following S3 buckets and associated static web sites have been created at:
https://s3.console.aws.amazon.com/s3/home

- docs.accordproject.org (http://docs.accordproject.org.s3-website-us-east-1.amazonaws.com)
- models.accordproject.org (http://models.accordproject.org.s3-website-us-east-1.amazonaws.com) 
- templates.accordproject.org (http://templates.accordproject.org.s3-website-us-east-1.amazonaws.com)

What needs to happen next is:
- [ ] Review and/or merge PR containing GitHub Actions for each repo's `master` branch. (@mttrbrts @jeromesimeon) 
- [ ] Create CloudFront Distributions for static sites. (@martinhalford)
- [ ] Create AWS hosted SSL Cert - no cost. (@martinhalford)
- [ ] Make DNS changes to AccordProject.org zone files to point at respective CloudFront Distros. (@mttrbrts @jeromesimeon)

**Comment by martinhalford** [comment]
@mttrbrts @jeromesimeon 

I am attempting to create a `*.accordproject.org` SSL certificate within the AWS Account for the Accord Project.  

We need this cert in order to enable AWS CloudFront in order to serve the static web sites over HTTPS.

AWS has sent a validation request to `admin@accordproject.org` email address.  

Can one of you please confirm this pending validation request?

You can login to the AWS Console and checkout the request in person, if you like.
https://console.aws.amazon.com/acm/home?region=us-east-1#/certificates/ab16ccef-fca2-4b5b-aec4-e872fe976fbf 

Thank you!!
...Martin

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/970336/151766479-1d3e146c-40b0-416c-a52c-47cb57b35e98.png">

**Comment by mttrbrts** [comment]
> @mttrbrts @jeromesimeon
> 
> I am attempting to create a `*.accordproject.org` SSL certificate within the AWS Account for the Accord Project.
> 
> We need this cert in order to enable AWS CloudFront in order to serve the static web sites over HTTPS.
> 
> AWS has sent a validation request to `admin@accordproject.org` email address.
> 
> Can one of you please confirm this pending validation request?
> 
> You can login to the AWS Console and checkout the request in person, if you like. https://console.aws.amazon.com/acm/home?region=us-east-1#/certificates/ab16ccef-fca2-4b5b-aec4-e872fe976fbf
> 
> Thank you!! ...Martin
> 
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/970336/151766479-1d3e146c-40b0-416c-a52c-47cb57b35e98.png">

Done
![image](https://user-images.githubusercontent.com/7544022/151825504-c75886ef-2609-4c80-addd-6d7d474bcfd9.png)

**Comment by martinhalford** [comment]
> Done ![image](https://user-images.githubusercontent.com/7544022/151825504-c75886ef-2609-4c80-addd-6d7d474bcfd9.png)

Thanks @mttrbrts !

**Comment by martinhalford** [comment]
@mttrbrts @jeromesimeon 

As we now have an SSL Certificate, I have created HTTPS CloudFront Distributions for the various S3 buckets.

There are:
Models: https://d1ht85ped1rq7k.cloudfront.net/
Docs: https://d2mvxkuux3rurm.cloudfront.net/
Templates: https://d3tro8cod408ug.cloudfront.net/

Please see notes in PRs raised against respective repos.  We will need add some additional "secrets" to the respective repos. See PRs for details.

Now all that needs to happen is configure the DNS zone files to use these new CloudFront URLs.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html

**Comment by martinhalford** [comment]
@jeromesimeon @mttrbrts 

The Template Studio static web site has been deployed to S3 and a PR raised.
https://github.com/accordproject/template-studio/pull/186 

Just needs the DNS changes to give it a proper URL.

The CF Distro URL is:
https://d31lzdnw1gfzn9.cloudfront.net/

**Comment by martinhalford** [comment]
@jeromesimeon @mttrbrts 

The Web Components Storybook static web site has been deployed to S3 and a PR raised.
https://github.com/accordproject/web-components/pull/372

Just needs the DNS changes to give it a proper URL.

The CF Distro URL for testing is:
https://d39ci3wc10irbe.cloudfront.net/

**Comment by martinhalford** [comment]
@jeromesimeon @mttrbrts

The Templatemark Dingus static web site has been deployed to S3 and a PR raised.
https://github.com/accordproject/markdown-transform/pull/478

Just needs the DNS changes to give it a proper URL.

The CF Distro URL for testing is:
https://defpqedhlibco.cloudfront.net/

**Comment by martinhalford** [comment]
- Create mapping from old URLs to new URLs (Martin)
- Update README.md 
- Update boilerplate.
- Being used in builds and testing. Working well. Reduced errors.

**Comment by martinhalford** [comment]
Mappings:

**1. docs.accordproject.org**
- **FQDN url:** https://docs.accordproject.org (**_note:_** same as old published url.)
- **cdn url:** https://d2mvxkuux3rurm.cloudfront.net
- **S3 hosting bucket url:**  http://docs.accordproject.org.s3-website-us-east-1.amazonaws.com 

**2. models.accordproject.org**
- **FQDN url:** https://models.accordproject.org (**_note:_** same as old published url.)
- **cdn url:** https://d1ht85ped1rq7k.cloudfront.net
- **S3 hosting bucket url:**  http://models.accordproject.org.s3-website-us-east-1.amazonaws.com

**3. templates.accordproject.org**
- **FQDN url:** https://templates.accordproject.org (**_note:_** same as old published url.)
- **cdn url:** https://d3tro8cod408ug.cloudfront.net
- **S3 hosting bucket url:**  http://templates.accordproject.org.s3.us-east-1.amazonaws.com

**4. studio.accordproject.org**
- **FQDN url:** https://studio.accordproject.org (**_note:_** same as old published url.)
- **cdn url:** https://d31lzdnw1gfzn9.cloudfront.net
- **S3 hosting bucket url:**  http://studio.accordproject.org.s3-website-us-east-1.amazonaws.com

**5. web-components.accordproject.org**
- **Old FQDN url:** https://ap-web-components.netlify.app
- **New FQDN url:** https://web-components.accordproject.org
- **cdn url:** https://d39ci3wc10irbe.cloudfront.net
- **S3 hosting bucket url:**  http://web-components.accordproject.org.s3-website-us-east-1.amazonaws.com

**6. templatemark-dingus.accordproject.org**
- **Old FQDN url:** https://templatemark-dingus.netlify.app
- **New FQDN url:** https://templatemark-dingus.accordproject.org
- **cdn url:** https://defpqedhlibco.cloudfront.net
- **S3 hosting bucket url:**  http://templatemark-dingus.accordproject.org.s3-website-us-east-1.amazonaws.com

**Comment by martinhalford** [comment]
All action items completed.
