### ISSUE TITLE
Automate social media posts

### ISSUE THREAD

**Issue by DianaLease** [accordproject/technical-steering-committee#51]
# Discussion 🗣

I'd like to propose setting up automatic social media posts.

## Context

The AP social media accounts could use some love. We could do something like nominate a "Social Media" chair to create content, but I wonder if a more sustainable strategy could be to set up some automatic posts based on our activity on GitHub or on our blog.

## Detailed Description

- Auto-post to Twitter and/or LinkedIn any time AP publishes a new blog post
- Auto-post when a new major version of Cicero / Concerto / etc is released?
- IFTTT may be a helpful tool to use

**Comment by mttrbrts** [comment]
How do we manage access to Social Media accounts?

**Comment by mttrbrts** [comment]
Reminders about working group call?

**Comment by DianaLease** [comment]
Some things that are possible with https://ifttt.com/. We could start with trying the free tier and see how far that gets us.
- If new vimeo video is uploaded, post a tweet (for tweeting weekly tech wg and tsc recordings)
- If new vimeo video is uploaded, post a message in Discord (automate posting recordings to Discord)
- If Google calendar event is starting, post a message in Discord (automate tech wg call reminders in Discord)
- If new WordPress post, post a link on LinkedIn (for automatically sharing blog posts)
- If new pinned message in a Discord channel, post a tweet

**Comment by mttrbrts** [comment]
Auto transcription of meeting recordings?

**Comment by mttrbrts** [comment]
Agreed to continue with manual publishing
