### ISSUE TITLE
Hosting for Accord Project Web Site

### ISSUE THREAD

**Issue by dselman** [accordproject/technical-steering-committee#6]
The Accord Project website http://accordproject.org is currently hosted on Wordpress on AWS.

We need to move this onto AP hosted infrastructure and ensure that the source code for the site is available and that we can receive pull requests against it.

**Comment by dselman** [comment]
@mttrbrts is investigating moving the site to Wordpress.com, so we can offload the server maintenance etc to them.

**Comment by martinhalford** [comment]
Related to #5

**Comment by martinhalford** [comment]
Hosting has been migrated. Done! :-)
